### PR TITLE
Add comet

### LINKED ISSUE #99: Add COMET
**Brief metric info**
COMET is proposed primarily as an MT evaluation metric through a trained model.
> COMET is an open-source framework for MT evaluation that can be used for two purposes:
>  - To evaluate MT systems with our currently available high-performing metrics (check: [COMET Metrics](https://unbabel.github.io/COMET/html/models.html#comet-metrics)).
>  - To train and develop new metrics.

**Meta information**
Please fill below if applicable:
- Repo/Custom implementation: https://github.com/Unbabel/COMET
- Python implementation available: [x]
- Paper: https://aclanthology.org/2020.emnlp-main.213/
- Huggingface: https://github.com/huggingface/datasets/blob/master/metrics/comet

### PR DESCRIPTION
**Pull request by devrimcavusoglu**
Closes #99.

### CODE REVIEW

**Comment by devrimcavusoglu** [comment]
Currently CI is failing and one potential reason to that is not disabling the multiprocessing while scoring. There is a bug in the comet implementation, see [this issue](https://github.com/Unbabel/COMET/issues/62).

**Comment by devrimcavusoglu** [comment]
Any ideas for CI failing @Sophylax ? Some notes below:
- Test preserves around 4.5 GB memory, this is a similar case with Prism
- [The PR](https://github.com/Unbabel/COMET/pull/63) addressing bug fix for the issue on unbabel/COMET is merged. Still with `num_workers=0` it is failing.

Any similar situations experienced with your tests @ricardorei ?

**Comment by ricardorei** [comment]
Yes I had some problems with testing COMET using CI. Have you tried running the test with a smaller model?

For example `[wmt21-cometinho-da`](https://github.com/Unbabel/COMET/blob/master/METRICS.md)?

**Comment by ricardorei** [comment]
which version of COMET are you currently using?

**Comment by ricardorei** [comment]
Nice! I am happy to help, tag me if you need something else.

I'll do that. Actually, I need to update all the documentation, it is extremely outdated...

**Comment by devrimcavusoglu** [comment]
Thanks @ricardorei, appreciate it. Thanks for the comment about the repo as well, yes one of the milestone is that supplying a diverse set of metrics to people to make the evaluation in NLP more properly :).

**Pull request merged**
