### PR TITLE
New metrics structure completed.

### PR DESCRIPTION
**Pull request by devrimcavusoglu**
New metrics structure allows user to create and define params for metrics as desired. Current metric classes in `metrics/` can be extended or completely new custom metric can be defined inheriting `jury.metrics.Metric`.

### CODE REVIEW

**Comment by fcakyon** [comment]
@devrimcavusoglu why is this test failing? https://github.com/obss/jury/pull/35/checks#step:10:19

**Comment by devrimcavusoglu** [comment]
> @devrimcavusoglu why is this test failing? https://github.com/obss/jury/pull/35/checks#step:10:19

Interesting. All checks seems passing for me, is it any spesific check or for all checks at same step ?

**Comment by fcakyon** [comment]
@devrimcavusoglu all checks fail at `tests/jury/test_jury.py::test_evaluate_concurrent FAILED                 [ 60%]`

**Review by fcakyon — APPROVED** [review]

**Review by cemilcengiz — APPROVED** [review]
LGTM!

**Pull request merged**
